import 'package:desy_genui/desy_genui.dart';
import 'package:desy_genui_example/genui_backend.dart';
import 'package:desy_genui_example/main.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('renders the dogfood catalog in the Desy chat shell', (
    tester,
  ) async {
    tester.view.physicalSize = const Size(800, 1400);
    tester.view.devicePixelRatio = 1;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
    await tester.pumpWidget(const DesyGenUiExampleApp());
    await tester.pump();

    expect(find.text('Dogfood registry connected'), findsOneWidget);
    expect(find.text('GENUI AGENT'), findsWidgets);
    expect(find.text('Generate UI'), findsOneWidget);
    expect(
      find.text('No generated UI event received yet.', skipOffstage: false),
      findsOneWidget,
    );
  });

  testWidgets('replaces the fixture with backend-generated A2UI', (
    tester,
  ) async {
    final backend = _FakeBackend();
    await tester.pumpWidget(DesyGenUiExampleApp(backend: backend));
    await tester.pump();

    await tester.enterText(find.byType(TextField), 'Build a generated result.');
    await tester.pump();
    await tester.tap(find.text('Generate UI'));
    await tester.pumpAndSettle();

    expect(
      (backend.turns.single as GenUiPromptTurn).text,
      'Build a generated result.',
    );
    expect(
      backend.catalog?.catalog.catalogId,
      'desy.design-system@0.2-experimental',
    );
    expect(find.text('Generated by a fake agent'), findsOneWidget);
    expect(find.text('Dogfood registry connected'), findsNothing);
    expect(find.textContaining('test-model · response-test'), findsOneWidget);

    await tester.tap(find.text('Generated by a fake agent'));
    await tester.pumpAndSettle();
    expect(backend.turns, hasLength(2));
    final actionTurn = backend.turns.last as GenUiActionTurn;
    expect(actionTurn.action.name, 'continue');
    expect(actionTurn.action.context['source'], 'fake-backend');
    expect(actionTurn.action.context['label'], 'Generated by a fake agent');
    expect(
      actionTurn.currentSurface.single['component'],
      'desy.component.button',
    );
    expect(find.text('Action handled by the agent'), findsOneWidget);
    final event = tester.widget<SelectableText>(
      find.byKey(const ValueKey('last-action'), skipOffstage: false),
    );
    expect(event.data, contains('"name":"continue"'));
    expect(event.data, contains('"source":"fake-backend"'));
    expect(event.data, contains('"label":"Generated by a fake agent"'));
  });

  testWidgets('app policy can keep a generated action local', (tester) async {
    final backend = _FakeBackend();
    await tester.pumpWidget(
      DesyGenUiExampleApp(backend: backend, shouldForwardAction: (_) => false),
    );
    await tester.pump();

    await tester.enterText(find.byType(TextField), 'Build a local action.');
    await tester.pump();
    await tester.tap(find.text('Generate UI'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Generated by a fake agent'));
    await tester.pumpAndSettle();

    expect(backend.turns, hasLength(1));
    expect(backend.turns.single, isA<GenUiPromptTurn>());
    expect(find.text('Generated by a fake agent'), findsOneWidget);
    final event = tester.widget<SelectableText>(
      find.byKey(const ValueKey('last-action'), skipOffstage: false),
    );
    expect(event.data, contains('"name":"continue"'));
  });
}

final class _FakeBackend implements GenUiBackend {
  final turns = <GenUiTurn>[];
  DesyGenUiCatalog? catalog;

  @override
  Future<GeneratedSurface> respond({
    required GenUiTurn turn,
    required DesyGenUiCatalog catalog,
  }) async {
    turns.add(turn);
    this.catalog = catalog;
    if (turn is GenUiActionTurn) {
      return const GeneratedSurface(
        model: 'test-model',
        responseId: 'response-action',
        components: [
          {
            'id': 'root',
            'component': 'desy.component.card',
            'title': 'Action handled by the agent',
            'body': 'The emitted action became a structured continuation.',
            'showBody': true,
          },
        ],
      );
    }
    return const GeneratedSurface(
      model: 'test-model',
      responseId: 'response-test',
      components: [
        {
          'id': 'root',
          'component': 'desy.component.button',
          'label': 'Generated by a fake agent',
          'outline': false,
          'enabled': true,
          'onPress': {
            'event': {
              'name': 'continue',
              'context': {'source': 'fake-backend'},
            },
          },
        },
      ],
    );
  }

  @override
  void close() {}
}
